name: flutter_quizzes
description: Flutter Quizzes is a Flutter package that allows you to create quizzes with images and text.
version: 1.0.2+1
homepage: https://github.com/Asilmaz/flutter_quizzes
repository: https://github.com/Asilmaz/flutter_quizzes
issue_tracker: https://github.com/Asilmaz/flutter_quizzes/issues
topics: [screenshots, image-capture, dynamic-image-generation]

environment:
  sdk: ">=3.3.0"
  flutter: ">=2.16.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ">=2.1.5"
  any_link_preview:
    git:
      url: https://github.com/sur950/any_link_preview.git
  open_filex: ">=4.6.0"
  gal: ">=2.3.1 "
  flutter_svg: ">=2.0.17"
  davinci:
    git:
      url: https://github.com/Staheos/davinci.git
  home_widget: '>=0.7.0'
  flutter_bta_functions:
    git:
      url: https://github.com/Staheos/flutter_bta_functions.git
  flutter_animate:
  page_transition:
  smooth_page_indicator:
  widget_zoom:


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/
    - assets/sats/
    - assets/sats/questions/
    - assets/sats/questions/rw/
    - assets/sats/questions/rw/Central-Ideas-and-Details/
    - assets/sats/questions/rw/Command-of-Evidence/
    - assets/sats/questions/rw/Cross-Text-Connections/
    - assets/sats/questions/rw/Form-Structure-and-Sense/
    - assets/sats/questions/rw/Inferences/
    - assets/sats/questions/rw/Rhetorical-Synthesis/
    - assets/sats/questions/rw/Text-Structure-and-Purpose/
    - assets/sats/questions/rw/Transitions/
    - assets/sats/questions/rw/Words-in-Context/
    - assets/sats/questions/rw/Boundaries/
    - assets/sats/start_images/

platforms:
  android:
  ios:
  web:
